baseURL = "http://10sr.github.io/b"
languageCode = "ja-jp"
hasCJKLanguage = true
theme = "lanyon-hugo"
publishDir = "../b"
relativeURLs = true
CanonifyURLs = true
uglyURLs = true
verbose = true
verboseLog = true

[params]
title = "10sr.github.io/b"
description = "10sr static blog"
